name: Go build placeholder

on:
  workflow_call:
    secrets:
      token:
        description: 'Secret token from caller workflow to access private packages'
        required: true

jobs:
  call-go-prerelease-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: get-is-release
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "GO_ARGS=build --snapshot" | tee -a "$GITHUB_ENV" 
          else
            echo "GO_ARGS=build --snapshot --skip-publish" | tee -a "$GITHUB_ENV" 
          fi
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        id: import_gpg
        with:
          gpg_private_key: ${{ secrets.KF_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.KF_GPG_PASSPHRASE }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: ${{ env.GO_ARGS }}
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GPG_TTY: $(tty)
