name: Go build placeholder

on:
  workflow_call:
    inputs:
      release_version:
        description: The release version to use when publishing a build
        required: false
        type: string
        default: 1.0.0 # for non-released builds
    secrets:
      token:
        description: 'Secret token from caller workflow to access private packages'
        required: true

jobs:
  call-go-prerelease-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Allow goreleaser to access older tag information.
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: get-is-release
        run: |
          if [[ ""="${{inputs.release_version}}" ]]; then
            echo "GO_ARGS=--skip-publish" | tee -a "$GITHUB_ENV" 
          else
            echo "GO_ARGS=" | tee -a "$GITHUB_ENV" 
          fi
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          args: ${{ env.GO_ARGS }}
        env:
          # GitHub sets the GITHUB_TOKEN secret automatically.
          GITHUB_TOKEN: ${{ secrets.token }}
          PAT_TOKEN: ${{ secrets.token }}

  call-go-release-workflow:
    if: inputs.release_version != ''
    runs-on: ubuntu-latest
    steps:
    - name: Go Build Release Placeholder
      run: echo "Go Build Release Placeholder"
