name: Configure Repository Release Branch Settings
#############################################################################################
# The following tasks should be performed whenever a release-* branch is created or updated
# - action-update-description
# - action-assign-topics
# - action-gh-teams-update 
# - action-set-branch-protection
# - action-set-repo-license
#############################################################################################
on: 
  workflow_call:
    secrets:
      token:
        description: 'Secret token from caller workflow to access repo'
        required: true
  create:
    branches:
      - 'release-*.*'


jobs:
  configure_repo:
    runs-on: ubuntu-latest
    name: Updating repository settings
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.token}}
      - name: Update topic from manifest:integration_type
        id: update-topic
        uses: keyfactor/action-assign-topics@v1.0
        with:
          token: ${{ secrets.token}}
      - name: Update description from manifest
        id: update-description
        uses: keyfactor/action-update-description@v1.0
        with:
          token: ${{ secrets.token}}
      - name: Update teams for non keyfactor-customer-private repos
        id: update-teams
        uses: keyfactor/action-gh-teams-update@v1.0
        with:
          token: ${{ secrets.token}}
  configure_branch:
    runs-on: ubuntu-latest
    name: Checkout the private action
    steps:
    - name: Checkout tools repo
      uses: actions/checkout@v4
      with:
        repository: keyfactor/action-set-branch-protection
        path: my-tools
        ref: v1
        token: ${{ secrets.token}}
    - name: Update the branch protection in this repository for ${{ github.event.ref}}
      id: update
      uses: ./my-tools
      with:
        repo-token: ${{ secrets.token}}
        protect-branch: ${{ github.event.ref}}
