name: Post Release Tasks
on: 
  workflow_call:
    secrets:
      token:
        description: 'Secret token from caller workflow to access repo'
        required: true
    

jobs:
  remove_prereleases:
    runs-on: ubuntu-latest
    name: Deleting prereleases
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.token}}
      - name: Run delete-prereleases action
        id: run-delete
        uses: keyfactor/action-delete-prereleases@dev
        with:
          repo-token: ${{ secrets.token}}
      - name: Display type
        id: display
        run: |
          echo ${{ steps.run-delete.output.repo-names}}
