name: Post release tasks
on: 
  workflow_call:
    inputs:
      REL_VER:
        type: string
        description: base tag for release versions
        required: true
    secrets:
      token:
        description: token
        required: true

jobs:
  clean-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Remove prereleases
        uses: Keyfactor/action-delete-prereleases@versioned-prereleases
        with:
          repo-token: ${{ secrets.V2BUILDTOKEN }}
          REL_VER: ${{ inputs.REL_VER }}
