# example workflow for Polaris scans using the Synopsys Action
# https://github.com/marketplace/actions/synopsys-action
name: CI Polaris Scanning 
on:
  workflow_call:
    secrets:
      token:
        description: 'Secret token from caller workflow to access private packages'
        required: true
    inputs:
      scan_branch:
        description: Incoming branch to release or main
        required: true
        type: string
      
  
  
  
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Polaris Scan
        uses: keyfactor/synopsys-action@v1.10.0
        with:
          ### SCANNING: Required fields
          polaris_server_url: 'https://polaris.synopsys.com'
          polaris_access_token: ${{ secrets.token }}
          polaris_assessment_types: "SCA,SAST"
          polaris_application_id: 'Integrations'
          polaris_project_id: ${{ github.event.repository.name }}
          polaris_branch_id: ${{ inputs.scan_branch }}
          
          ## SCANNING: Optional fields
          polaris_application_name: 'Integrations'
          polaris_project_name: ${{ github.event.repository.name }}
          polaris_assessment_mode: "SOURCE_UPLOAD"
          polaris_branch_name: ${{ github.scan_branch }}
          
          # ## PULL REQUEST COMMENTS: Uncomment below to enable
          # polaris_prComment_enabled: false
          # github_token: ${{ secrets.GITHUB_TOKEN }} # Required when PR comments is enabled