name: Post release tasks
on: 
  workflow_call:
    secrets:
      token:
        description: token
        required: true
    inputs:
      branchname:
        description: Release branch tag being merged to main
        required: true
        type: string

jobs:
  clean-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Remove prereleases
        uses: Keyfactor/action-delete-prereleases@v1.0
        with:
          token: ${{ secrets.token }}

      - name: Create PR to main
        uses: Keyfactor/action-pull-request@v0.5.5
        with:
          token: ${{ secrets.token }}
          source_branch: ${{ inputs.branchname }}
          target_branch: main
          title: Merge ${{ inputs.branchname }} to main
          body: "Merge ${{ inputs.branchname }} to main - Automated PR"
