name: Post release tasks
on: 
  workflow_call:
    secrets:
      token:
        description: token
        required: true

jobs:
  clean-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Remove prereleases
        uses: keyfacor/action-delete-prereleases@v1.0
        with:
          token: ${{ secrets.V2BUILDTOKEN }}
