name: Update repository description
on:
  workflow_call:
    secrets:
      token:
        description: 'Secret token from caller workflow to access SDK repo'
        required: true
        
jobs:
  read_type:
    runs-on: ubuntu-latest
    name: A CI job to read the description from integration-manifest.json
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repo-token: ${{ secrets.token}}
      - name: Update description from integration-manifest.json
        id: update
        uses: keyfactor/action-update-description@v1.0
        with:
          input-file: integration-manifest.json
          repo-token: ${{ secrets.token}}
      - name: Display type
        id: display
        run: |
          echo ${{ steps.read.output.dbg-out}}
