name: Bootstrap Starter Workflow
on:
  workflow_call:
    #inputs: 
    #  buildtype: 
    #    description: 'Platform to build'
    #    required: true
    #    type: string  
    #  release_dir: 
    #    description: 'release_dir property from integration-manifest.json'
    #    required: true
    #    type: string  
    #  update_catalog: 
    #    description: 'update_catalog property from integration-manifest.json'
    #    required: true
    #    type: string  

jobs:
  call-assign-from-json-workflow:
    uses: Keyfactor/actions/.github/workflows/assign-env-from-json.yml@main

  call-get-primary-language:
    outputs:
      primary_language: ${{ steps.read.outputs.primary_language }}
    runs-on: ubuntu-latest
    name: Detect Primary Language
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Read primary language
        id: read
        uses: fiddlermikey/action-get-primary-language@v1.0
        with:
          token: ${{ secrets.SDK_SYNC_PAT}}
      - name: Display type
        id: display
        run: |
          echo "primary_language=${{ steps.read.outputs.primary_language}}" | tee -a "$GITHUB_OUTPUT" | tee -a $GITHUB_STEP_SUMMARY

  call-create-github-release-workflow:
    uses: Keyfactor/actions/.github/workflows/github-release.yml@support-hotfixes

  call-dotnet-build-and-release-workflow:
    needs: [call-get-primary-language, call-assign-from-json-workflow, call-create-github-release-workflow]
    if: needs.call-get-primary-language.outputs.primary_language == 'C#'
    uses: keyfactor/actions/.github/workflows/dotnet-build-and-release.yml@support-hotfixes
    with:
      release_version: ${{ needs.call-create-github-release-workflow.outputs.release_version }}
      release_url: ${{ needs.call-create-github-release-workflow.outputs.release_url }}
      release_dir: ${{ needs.call-assign-from-json-workflow.outputs.release_dir }}

    secrets: 
      token: ${{ secrets.SDK_SYNC_PAT }}

  call-go-build-and-tag-workflow:
    needs: [call-get-primary-language, call-assign-from-json-workflow, call-create-github-release-workflow]
    if: needs.call-get-primary-language.outputs.primary_language == 'Go'
    uses: fiddlermikey/actions/.github/workflows/go-build-and-tag.yml@dev
    with:
      release_version: ${{ needs.call-create-github-release-workflow.outputs.release_version }}


    secrets: 
      token: ${{ secrets.SDK_SYNC_PAT }}

  #call-generate-readme-workflow:
  #  if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
  #  uses: Keyfactor/actions/.github/workflows/generate-readme.yml@main
  #  secrets:
  #    token: ${{ secrets.APPROVE_README_PUSH }}

  #call-update-catalog-workflow:
  #  if: inputs.update_catalog == 'True' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
  #  uses: Keyfactor/actions/.github/workflows/update-catalog.yml@main
  #  secrets: 
  #    token: ${{ secrets.SDK_SYNC_PAT }}
