name: Bootstrap Starter Workflow
on:
  workflow_call:
    secrets:
      token:
        description: 'GitHub token'
        required: true
      age-key:
        description: 'key for decrypting age-encrypted secrets'
        required: true
    inputs:
      integration-type:
        description: 'Type of integration (go, dotnet, helm)'
        required: true
        type: choice
        options:
          - go
          - dotnet
          - helm
        
permissions:
  packages: write
  pull-requests: write
  contents: write

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    if: ${{ inputs.integration-type == 'dotnet' }}

    steps:
      - name: Call Build and Pack Action
        uses: keyfactor/actions/build-and-pack@indrora/nextgen-actions
        matrix:
           dotnet-version: ['8.0', '10.0']
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          src-dir: 'RemoteFile'
          github-token: ${{ secrets.token }}