name: Merge Orchestrator store_types.json
on: 
  workflow_call:
    secrets:
      token:
        description: token
        required: true

jobs:
  merge_json_job:
    runs-on: ubuntu-latest
    name: Merge json files
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.token }}  
          path: './json-temp/'  
          repository: 'Keyfactor/kfutil' 

      - name: Merge input-file into library-file json data
        id: merge-json
        uses: Keyfactor/actions-merge-storetypes@v1.0.2
        with:
          input-file: integration-manifest.json
          library-file: ./json-temp/store_types.json

      - uses: Keyfactor/add-and-commit@v9.1.3
        with:
          author_name: 'Keyfactor'
          author_email: 'keyfactor@keyfactor.com'
          branch: 'main'
          message: ${{ format('Merged the {0} stores-type.json', github.event.repository.name) }}
          add: 'store_types.json'
          cwd: './json-temp/'

  create_certstore_stub:
    runs-on: ubuntu-latest
    name: Create store_types stub for readme
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.token }}

      - uses: Keyfactor/action-create-storetype-md@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          

      - uses: Keyfactor/add-and-commit@v9.1.3
        with:
          author_name: 'Keyfactor'
          author_email: 'keyfactor@keyfactor.com'
          message: ${{ format('Created the {0} store_type readme stub md', github.event.repository.name) }}
          add: ./readme-src/store-types-tables.md --force
